### ISSUE TITLE
next.config with both settings and mdx

### ISSUE THREAD

**Issue by perryd01** [Bitsnoxx/CampKnut#41]

**Comment by Bitsnoxx** [comment]
This was fixed in #40, closing.

**Comment by perryd01** [comment]
withMDX is exported, but nextConfig isn't.

https://github.com/Bitsnoxx/CampKnut/blob/8e23284f4f35d8aeb18ef24d660e17aa1a8dc3c6/next.config.js#L32-L34

These are not being used currently.

https://github.com/Bitsnoxx/CampKnut/blob/8e23284f4f35d8aeb18ef24d660e17aa1a8dc3c6/next.config.js#L7-L15
